component: scf
name: get-user-info
inputs:
  description: 获取用户详细信息
  runtime: Nodejs18.15
  memorySize: 256
  handler: index.main
  installDependency: true
  timeout: 20
  eip: false
  publicAccess: true
  vpcConfig:
    vpcId: ""
    subnetId: ""
  events: []
  layers: []
  initTimeout: 65
  protocolParams: null
  protocolType: "" 