component: scf
name: delete-daily-menu-if-empty
inputs:
  description: 如无菜品则删除每日菜单
  runtime: Nodejs18.15
  memorySize: 256
  handler: index.main
  installDependency: true
  timeout: 20
  eip: false
  publicAccess: true
  vpcConfig:
    vpcId: ""
    subnetId: ""
  events: []
  layers: []
  initTimeout: 65
  protocolParams: null
  protocolType: "" 