component: scf
name: get-family-daily-menu-by-date
inputs:
  description: 获取家庭某天每日菜单
  runtime: Nodejs18.15
  memorySize: 256
  handler: index.main
  installDependency: true
  timeout: 20
  eip: false
  publicAccess: true
  vpcConfig:
    vpcId: ""
    subnetId: ""
  events: []
  layers: []
  initTimeout: 65
  protocolParams: null
  protocolType: "" 